In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [3]:
len(words)

32033

In [4]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [5]:
# build the dataset

block_size = 3
def build_dataset(words):  
  X, Y = [], []
  for w in words:
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      context = context[1:] + [ix]
      print(''.join(itos[i] for i in context), '--->', itos[ix])
  return torch.tensor(X), torch.tensor(Y)
  
X,Y = build_dataset(words)

..e ---> e
.em ---> m
emm ---> m
mma ---> a
ma. ---> .
..o ---> o
.ol ---> l
oli ---> i
liv ---> v
ivi ---> i
via ---> a
ia. ---> .
..a ---> a
.av ---> v
ava ---> a
va. ---> .
..i ---> i
.is ---> s
isa ---> a
sab ---> b
abe ---> e
bel ---> l
ell ---> l
lla ---> a
la. ---> .
..s ---> s
.so ---> o
sop ---> p
oph ---> h
phi ---> i
hia ---> a
ia. ---> .
..c ---> c
.ch ---> h
cha ---> a
har ---> r
arl ---> l
rlo ---> o
lot ---> t
ott ---> t
tte ---> e
te. ---> .
..m ---> m
.mi ---> i
mia ---> a
ia. ---> .
..a ---> a
.am ---> m
ame ---> e
mel ---> l
eli ---> i
lia ---> a
ia. ---> .
..h ---> h
.ha ---> a
har ---> r
arp ---> p
rpe ---> e
per ---> r
er. ---> .
..e ---> e
.ev ---> v
eve ---> e
vel ---> l
ely ---> y
lyn ---> n
yn. ---> .
..a ---> a
.ab ---> b
abi ---> i
big ---> g
iga ---> a
gai ---> i
ail ---> l
il. ---> .
..e ---> e
.em ---> m
emi ---> i
mil ---> l
ily ---> y
ly. ---> .
..e ---> e
.el ---> l
eli ---> i
liz ---> z
iza ---> a
zab ---> b
abe ---> e
bet ---> t
eth ---> h
th. ---> .

In [6]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([228146, 3]), torch.int64, torch.Size([228146]), torch.int64)

### Embedding Tablosu ve İndeksleme

In [7]:
C = torch.randn((27, 2))

In [8]:
emb = C[X]
emb.shape

torch.Size([228146, 3, 2])

In [9]:

x_one_hot = F.one_hot(torch.tensor(5), num_classes=27).float()
out_matmul = x_one_hot @ C
out_index = C[5]

print("One-Hot:", out_matmul)
print("indexleme:", out_index)
print("Tamamen eşit mi?:", torch.allclose(out_matmul, out_index))

One-Hot: tensor([-0.7270, -1.1738])
indexleme: tensor([-0.7270, -1.1738])
Tamamen eşit mi?: True


In [10]:
x_one_hot

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
out_matmul

tensor([-0.7270, -1.1738])

In [12]:
out_index

tensor([-0.7270, -1.1738])